name: Build and Push Docker Image

on:
  push:
    branches:
      - dev
env:
  DOCKER_IMAGE_TAG_NAME: sesacsemi2-front

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. GitHub repository에서 코드 가져오기
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Node.js 환경 설정 (버전 17 사용)
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      # 3. 의존성 설치
      - name: Install dependencies
        run: npm ci

      # 4. 빌드 실행 (React 앱을 빌드하여 최적화된 build 폴더 생성)
      - name: Build React app
        run: npm run build

      # 5. Dockerfile을 사용하여 Docker 이미지 빌드
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE_TAG_NAME }}:latest .

      # 6. Docker Hub 로그인
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 7. Docker 이미지 푸시
      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE_TAG_NAME }}:latest

      # 8. QEMU(Quick Emulator)를 설정
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
